spring.application.name=prod

spring.datasource.url=jdbc:mysql://localhost:3306/production?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.http=DEBUG
fast.api.base.url=http://127.0.0.1:8000

logging.level.com.prod.services.PostServiceImpl=TRACE
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{hh:mm:ss dd:MM:yyyy}){faint} -%t %clr([%level]) -- %clr(%c){magenta} %m %n
#logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){yellow} %clr(%-5level){} %clr(%c{1}){cyan} - %msg%n

logging.file.name=app.log
logging.config=classpath:spring-rollback.xml

#actuator

management.endpoints.web.exposure.include=*