spring.application.name=prod

spring.datasource.url=jdbc:mysql://localhost:3306/production?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.http=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.prod=DEBUG
fast.api.base.url=http://127.0.0.1:8000



logging.level.com.prod.services.PostServiceImpl=TRACE
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{hh:mm:ss dd:MM:yyyy}){faint} -%t %clr([%level]) -- %clr(%c){magenta} %m %n
#logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){yellow} %clr(%-5level){} %clr(%c{1}){cyan} - %msg%n
# Sets logger name to 40 characters, left-aligned, and handles the message
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %cyan(%-40logger{40}) : %msg%n

#logging.file.name=app.log
#logging.config=classpath:spring-rollback.xml

#actuator

spring.security.user.name=user
spring.security.user.password=user
management.endpoints.web.exposure.include=*

jwt.secret=hqwdjnqdkwqdnqwdjnqndwjdnqdu382u9uedj3ij9m21e9wj129ue129ewjs921prm31ne2udg13yd3i1hdu1oj2ond12he3ud1hio12ws